# БАЗОВЫЙ вариант, использует зависимости разработки

# Актуальный образ CUDA 12.8 на Ubuntu 22.04
FROM nvidia/cuda:12.8.0-runtime-ubuntu22.04

# Установка Python 3.10, pip, системных библиотек (OpenCV, git)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3-pip \
    libgl1-mesa-glx \
    libglib2.0-0 \
    git \
    && ln -s /usr/bin/python3.10 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем requirements.txt до установки пакетов
COPY requirements-dev.txt .

# Устанавливаем PyTorch 2.8.0 + torchvision 0.23.0 с индексом CUDA 12.8
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir --no-compile \
    torch==2.8.0 torchvision==0.23.0 \
    --index-url https://download.pytorch.org/whl/cu128

# Устанавливаем остальные зависимости из requirements-dev.txt (с кэшированием)
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir --no-compile -r requirements-dev.txt    
    

# Клонируем SAM2 в /app/sam2 (на один уровень с src) и устанавливаем
RUN git clone --depth 1 https://github.com/serg-kas/sam21.git /app/sam21 && \
    pip install --no-cache-dir -e /app/sam21 && \
    rm -rf /app/sam21/.git
    

# Копируем исходный код приложения
COPY src/ ./src/

CMD ["python", "src/app.py"]

