# Dockerfile.cpu – для запуска на системах без GPU

FROM ubuntu:22.04

# Установка Python 3.10 и pip
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3-pip \
    && ln -s /usr/bin/python3.10 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc/* /usr/share/man/* /usr/share/locale/* /usr/share/info/*

WORKDIR /app

# Копируем файл с зависимостями
COPY requirements-prod.txt .

# Установка PyTorch CPU-версии и остальных пакетов
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir --no-compile numpy==1.26.4 && \
    pip install --no-cache-dir --no-compile \
    torch==2.8.0 torchvision==0.23.0 \
    --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir --no-compile -r requirements-prod.txt

# Клонирование и установка SAM2 (исходный код)
RUN apt-get update && apt-get install -y --no-install-recommends \
        git build-essential python3.10-dev \
    && git clone --depth 1 https://github.com/serg-kas/sam21.git /app/sam21 \
    && pip install --no-cache-dir --no-build-isolation -e /app/sam21 \
    && rm -rf /app/sam21/.git \
    && apt-get purge -y git build-essential python3.10-dev \
    && apt-get autoremove -y --purge \
    && rm -rf /var/lib/apt/lists/* /root/.cache/pip/* /tmp/* /var/tmp/*

# Копирование исходного кода приложения
COPY src/ ./src/

CMD ["python", "src/app.py"]

